// Code generated by mockery v2.33.1. DO NOT EDIT.

package port

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockIpService is an autogenerated mock type for the IpService type
type MockIpService struct {
	mock.Mock
}

// GetHostIp provides a mock function with given fields: ctx
func (_m *MockIpService) GetHostIp(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyDnsRecord provides a mock function with given fields: ctx, ip, domainName
func (_m *MockIpService) VerifyDnsRecord(ctx context.Context, ip string, domainName string) (bool, error) {
	ret := _m.Called(ctx, ip, domainName)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, ip, domainName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, ip, domainName)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, ip, domainName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockIpService creates a new instance of MockIpService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIpService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIpService {
	mock := &MockIpService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
