// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package queries

import (
	"database/sql"
)

type DnsInfo struct {
	Domain    string
	SubDomain sql.NullString
	Ip        sql.NullString
	NodeName  sql.NullString
	Email     sql.NullString
}
